#!/usr/bin/env bash

# https://formulae.brew.sh/formula/tree
command -v tree >/dev/null 2>&1 || { echo >&2 "I require tree but it's not installed. Aborting."; exit 1; }
# https://formulae.brew.sh/formula/gomplate
command -v gomplate >/dev/null 2>&1 || { echo >&2 "I require gomplate but it's not installed. Aborting."; exit 1; }

ignore_files=".git|_templates|customize|README.md"

for input_file in `tree -I "${ignore_files}" -Ffai --noreport`
do
  if [ ! -d "${input_file}" ]; then
    echo "Processing file: ${input_file}"
    gomplate \
      -f "${input_file}" \
      -o "${input_file}" \
      --left-delim "<<[" \
      --right-delim "]>>" \
      -c cus=./customize.json
  fi
done
 
if [ -f "./configs.json" ]; then
  # Merge configs and only add new properties to the existing config file.
  contents="$(jq -s '.[0] * .[1]' initial_configs.json configs.json)" && echo "${contents}" > configs.json
else
  mv initial_configs.json configs.json
fi

if [ ! -f "./package.json" ]; then
  mv initial_package.json package.json
fi

# Remove previous GitHub source
rm -rf .github

# Move GH folder
mv github .github

# Clean up / implode
rm README.md
rm customize
rm initial_configs.json
rm initial_package.json
rm customize.json
