#!/usr/bin/env bash

# https://formulae.brew.sh/formula/tree
command -v tree >/dev/null 2>&1 || { echo >&2 "I require tree but it's not installed. Aborting."; exit 1; }
# https://formulae.brew.sh/formula/gomplate
command -v gomplate >/dev/null 2>&1 || { echo >&2 "I require gomplate but it's not installed. Aborting."; exit 1; }

ignore_files=".git|_templates|customize|README.md"

for input_file in `tree -I "${ignore_files}" -Ffai --noreport`
do
  if [ ! -d "${input_file}" ]; then
    echo "Processing file: ${input_file}"
    gomplate \
         -f "${input_file}" \
         -o "${input_file}" \
         --left-delim "<<[" \
         --right-delim "]>>" \
         -c cus=./customize.json
  fi
done

# Remove previous GitHub source
rm -rf .github

# Move GH folder
mv github .github

# Clean up / implode
rm README.md
rm customize
rm customize.json

