name: Auto update generated library
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

  # Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook
jobs:
  update-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Generate code
        run: chmod +x ./generate.sh && ./generate.sh

      - name: Set Environment Variables from generator file
        uses: ./.github/actions/setvars
        with:
          varFilePath: ./.github/variables/generator.env
      # Follow conventional commit for PR's to ensure accurate updates
      - name: Create pull request for major version if needed
        if: ${{env.major_version_change == 'true'}}
        uses: peter-evans/create-pull-request@v4
        with:
          title: "feat!: major version change"
          body: ${{env.commit_message}}

      - name: Create pull request for minor version if needed
        if: ${{env.minor_version_change == 'true'}}
        uses: peter-evans/create-pull-request@v4
        with:
          title: "feat: minor version change"
          body: ${{env.commit_message}}

      - name: Create pull request for patch version if needed
        if: ${{env.patch_version_change == 'true'}}
        uses: peter-evans/create-pull-request@v4
        with:
          title: "fix: patch version change"
          body: ${{env.commit_message}}