name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: 'Release NPM, GitHub'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install dependencies
        run: npm ci
      - name: Build library
        run: npm run build
      - name: Get version from package.json before release step
        id: initversion
        run: echo "::set-output name=version::$(npm run get-version --silent)"
      - name: Release to NPM and GitHub
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: GamingEventapiBot
          GIT_AUTHOR_EMAIL: gamingeventapi@gmail.com
          GIT_COMMITTER_NAME: GamingEventapiBot
          GIT_COMMITTER_EMAIL: gamingeventapi@gmail.com
        run: npm run release
